task01 with tests
mirmozavr/EPAMHW pull request #1
Opened 2021-03-01 19:39 UTC by mirmozavr

**hw1 task01**
with tests

2021-03-02 21:44 UTC, Cjkjvfnby requested changes
Almost there, see comments

2021-03-02 21:44 UTC, Cjkjvfnby commented on hw1/task01/test_calculator.py
> +    [
Please add simple positive examples

2021-03-02 21:58 UTC, mirmozavr commented on hw1/task01/test_calculator.py
> +    [
Will do

2021-03-03 17:22 UTC, Cjkjvfnby approved these changes

2021-03-04 17:54 UTC, merged