Hw2 task05
mirmozavr/EPAMHW pull request #10
Opened 2021-03-05 18:55 UTC by mirmozavr

2021-03-05 19:53 UTC, Cjkjvfnby requested changes

2021-03-05 19:53 UTC, Cjkjvfnby commented on hw2/task05/hw2_task05.py
> +    it_obj: str, start: str = None, end: str = None, step: int = 1
Please follow the description, not by example.  `any iterable of unique values`  is not only str

2021-03-05 19:53 UTC, Cjkjvfnby commented on hw2/task05/hw2_task05.py
> +    for i in range(start, end, step):
How else could you slice iterable to get the required list?

2021-03-06 23:26 UTC, Cjkjvfnby commented
This PR shows me only partially changed files.   Looks like you have merged the first implementation to the master. Please fix it.

2021-03-06 23:26 UTC, Cjkjvfnby requested changes
@mirmozavr, please check the comment:

https://github.com/mirmozavr/EPAMHW/pull/9#discussion_r588637141

2021-03-07 09:36 UTC, mirmozavr commented
@Cjkjvfnby I forgot to checkout from master to this branch at 1st iteration. But this branch do have all versions of task files. I plan to resolve conflicts with master branch after this branch approval. Right?

2021-03-08 14:22 UTC, Cjkjvfnby commented
I expect that `hw2_task05.py ` present in this branch and not present in `master` branch. 

In this case diff will show me the whole file.  Now I can see the difference between the version in this branch and the version in master.

2021-03-08 15:00 UTC, mirmozavr commented
Removed files that belong to this branch from 'master'

2021-03-08 16:13 UTC, Cjkjvfnby commented
> Removed files that belong to this branch from 'master'

Did it solve the initial problem in the https://github.com/mirmozavr/EPAMHW/pull/10/files ?

Looks like you need to merge master to this branch.

2021-03-08 21:05 UTC, Cjkjvfnby approved these changes

2021-03-15 18:06 UTC, merged