Hw3_t04
mirmozavr/EPAMHW pull request #11
Opened 2021-03-06 11:18 UTC by mirmozavr

2021-03-06 11:32 UTC, mirmozavr commented
Need assistance with module imports in a right way with sys.path appends or__init__.py files

2021-03-07 08:14 UTC, Cjkjvfnby commented
> Need assistance with module imports in a right way with sys.path appends or__init__.py files

It is a quite vague request.  And you will get a vague answer:  import them in the right way.

To get a more precise answer please add more info to the question:  What do you want to achieve? What is blocking you?  What have you tried so far?

2021-03-07 17:09 UTC, mirmozavr commented
In this homework i decided to separate all test files into dedicated test folder. To fix imports for github i tried appending current file directory to sys.path, than addint __init__.py to folders.

2021-03-08 14:49 UTC, Cjkjvfnby commented
> In this homework i decided to separate all test files into dedicated test folder. 

I am not sure that this change is present in the branch.

> To fix imports for github 

You can run `pytest` locally in the root directory of the project.  It should produce the same result as on GitHub. 

Put `__init__.py` to folders with your homework, and don't put them to folders with tests.

PS. Please press the preview button before posting the comments. Use ticks around special names like `__inti__.py` (tick -> ` )

2021-03-08 15:42 UTC, mirmozavr commented
> I am not sure that this change is present in the branch.
The tree looks like this.
├───hw3
│   ├───tests
│   │   └───test_files.py
│   └───task_files.py

All imports had worked and tests had passed on Github

2021-03-08 16:22 UTC, Cjkjvfnby requested changes

2021-03-08 16:22 UTC, Cjkjvfnby commented on hw3/hw3_t04.py
> +    return number == reduce(
Do you know why reduce was hidden?  Because it is overused.  You can use another built-in function.

2021-03-08 16:22 UTC, Cjkjvfnby commented on hw3/hw3_t04.py
> +        map(lambda symbol: int(symbol) ** power, str(number)),
You can replace lamba + map with a list comprehension.

2021-03-08 16:22 UTC, Cjkjvfnby commented
> All imports had worked and tests had passed on Github

I don't think that you need any assistance with it.

2021-03-08 21:08 UTC, Cjkjvfnby approved these changes

2021-03-16 14:39 UTC, merged