Hw4 task01
mirmozavr/EPAMHW pull request #13
Opened 2021-03-10 14:50 UTC by mirmozavr

Open text, read the first line

2021-03-10 16:08 UTC, Cjkjvfnby requested changes
I have updated the task description to clarify what I expect a generation of the test files inside the tests.

2021-03-10 16:08 UTC, Cjkjvfnby commented on hw4/hw4_t01.py
> +        raise ValueError("Error text")
Question text

2021-03-10 16:08 UTC, Cjkjvfnby commented on hw4/hw4_t01.py
> +        rmtree(os.path.dirname(__file__) + "/__pycache__", ignore_errors=True)
> all temporary files are removed after a test run

It is not about these files. Only about files you have created. 

After test run means only after the test run, not during the function call.

2021-03-10 16:08 UTC, Cjkjvfnby commented on hw4/tests/test_hw4_t01.py
> +    assert read_magic_number(os.path.dirname(__file__) + "/data3.txt") is False
All `data?.txt` looks the same for me. But some of them are True and others False.  Please make names more descriptive.

2021-03-10 16:08 UTC, Cjkjvfnby commented on hw4/hw4_t01.py
> + - how to clean up after tests
Have you learned it?

2021-03-16 20:34 UTC, Cjkjvfnby requested changes
Some cosmetic comments.  

Please describe how cleanup works.

2021-03-16 20:34 UTC, Cjkjvfnby commented on hw4/hw4_t01.py
> +            return False
Can you simplify it?

2021-03-16 20:34 UTC, Cjkjvfnby commented on hw4/tests/test_hw4_t01.py
> +        read_magic_number(directory / "missing_file.txt")
Why do you need a directory here?

2021-03-16 21:11 UTC, mirmozavr commented
Quote from docs.pytest.org
Temporary directories are by default created as sub-directories of the system temporary directory. The base name will be pytest-NUM where NUM will be incremented with each test run. Moreover, entries older than 3 temporary directories will be removed.

2021-03-16 22:39 UTC, Cjkjvfnby approved these changes

2021-03-17 11:50 UTC, merged