Hw3 t03
mirmozavr/EPAMHW pull request #15
Opened 2021-03-13 17:49 UTC by mirmozavr

Filter function

2021-03-13 17:56 UTC, mirmozavr commented on hw3/tests/test_hw3_t03.py
> +    )
This one.

2021-03-14 20:06 UTC, Cjkjvfnby requested changes
Please make test names according to my comments. 

Please remove unused items from tests fixtures if it is not a subject of testing.  Keep test items as small as possible.

2021-03-14 20:06 UTC, Cjkjvfnby commented on hw3/hw3_t03.py
> +        self.functions = list(args)
Why list?

2021-03-14 20:06 UTC, Cjkjvfnby commented on hw3/tests/test_hw3_t03.py
> +def test_polly():
Who is Polly?   

This is no a filter for characters, it is a general-purpose filter. Characters are used as an example.

You have key, value, and item, so please build your positive and negative test around these terms.

2021-03-15 18:25 UTC, mirmozavr commented on hw3/hw3_t03.py
> +        self.functions = list(args)
List is ready for addition. But in this case, it should stay a tuple.

2021-03-15 21:15 UTC, Cjkjvfnby approved these changes
I am not happy with the test names, but it is a task3.

2021-03-15 21:15 UTC, Cjkjvfnby commented on hw3/tests/test_hw3_t03.py
> +def test_positive_for_1_subject():
It looks more like a COVID-19 test.

2021-03-15 21:15 UTC, Cjkjvfnby commented on hw3/tests/test_hw3_t03.py
> +def test_both_characters_by_diff_key_value_pairs():
Don't try to shorten words. Especially such commonly used in [IT](https://git-scm.com/docs/git-diff).

2021-03-15 21:15 UTC, Cjkjvfnby commented on hw3/tests/test_hw3_t03.py
> +def test_with_non_existent_value():
`non_existent` sounds way too philosophical. I'd prefer missing or absent.

2021-03-16 14:40 UTC, merged