Hw7 t01
mirmozavr/EPAMHW pull request #24
Opened 2021-03-25 14:55 UTC by mirmozavr

Element search in nested dict

2021-03-25 21:17 UTC, Cjkjvfnby requested changes
Please check that you have implemented all requirements.

2021-03-27 18:25 UTC, Cjkjvfnby requested changes
In general, I am happy with the solution. But there is some controversial moment.  You have not asked how to deal with it and implement one solution, so let's do it in a different way.  

First, we need to find a class that could be treated differently in the context of the task. And after that implement handling of both behaviours.

2021-03-27 19:44 UTC, mirmozavr commented
I had thoughts about search in strings. Like "RED" in "Roses are RED violets are Blue". Should we do this?

2021-03-27 19:57 UTC, Cjkjvfnby commented
> I had thoughts about search in strings. Like "RED" in "Roses are RED violets are Blue". Should we do this?

No, it violates the rules.  The idea is that string can be treated as a collection. 

```python
find_occurrences({"say": "WAAAGH!"}, "A") ==  3
```

2021-03-27 20:14 UTC, mirmozavr commented
So if we are looking for a single non-digit symbol - treat strings as iterable?

2021-03-28 23:33 UTC, Cjkjvfnby requested changes

2021-03-28 23:33 UTC, Cjkjvfnby commented on hw7/hw7_t01.py
> +def parse_collection(parsed_collection: Union[list, set, tuple], element: Any) -> int:
Have you missed anything?

2021-03-28 23:33 UTC, Cjkjvfnby commented on hw7/hw7_t01.py
> +    return counter
It could be done much simpler.

2021-03-29 16:03 UTC, mirmozavr commented on hw7/hw7_t01.py
> +def parse_collection(parsed_collection: Union[list, set, tuple], element: Any) -> int:
Yes

2021-03-29 16:03 UTC, mirmozavr commented on hw7/hw7_t01.py
> +    return counter
And yes

2021-03-29 20:30 UTC, Cjkjvfnby approved these changes

2021-03-29 20:30 UTC, Cjkjvfnby commented on hw3/tests/test_hw3_t02.py
> +"""from hw3.hw3_t02 import slow_calc_500_numbers.
See pytest mark features. Probably it is named skip.

2021-03-30 17:36 UTC, merged